import { AppsScriptFormTransport, PengantaranApi } from './api-client.js?v=5.0.1-hf1';

const $=id=>document.getElementById(id);
const state={transport:null,api:null,stop:false,report:null,tokens:{},users:{},created:[],baseId:'',master:null};
const tests=[
  ['backend','Backend & role login','Ping backend dan validasi FARMASI/KURIR/ADMIN/MANAJEMEN.'],
  ['privacy','Privasi antrean Kurir','Paket SIAP tidak boleh mengandung nama, RM, alamat, atau nomor pasien sebelum claim.'],
  ['duplicate','Validasi duplikasi','No. RM aktif yang sama harus meminta konfirmasi dan tidak membuat baris kedua otomatis.'],
  ['race','Perebutan tugas','Dua kurir claim paket yang sama bersamaan; tepat satu yang boleh berhasil.'],
  ['code','Penerimaan dengan kode','Kode salah ditolak; kode benar menyelesaikan pengantaran terverifikasi.'],
  ['manual','Tanpa kode + verifikasi manual','Penyerahan tanpa kode masuk antrean Admin lalu dapat diverifikasi manual.'],
  ['failed','Gagal antar','Alasan dan tindak lanjut gagal tercatat serta masuk riwayat Kurir.'],
  ['incident','Kendala Kurir','Kendala aktif → selesai → menunggu verifikasi Admin → diverifikasi.'],
  ['management','KPI Manajemen','Dashboard periode hari ini membaca hasil regresi dari data agregat.'],
  ['audit','Audit Admin','Jejak aktivitas sistem tetap terbaca setelah skenario sensitif.']
];

function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function sleep(ms){return new Promise(r=>setTimeout(r,ms));}
function nowId(){const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}${p(d.getMonth()+1)}${p(d.getDate())}-${p(d.getHours())}${p(d.getMinutes())}${p(d.getSeconds())}`;}
function localDate(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function log(msg,data){const line=`[${new Date().toLocaleTimeString('id-ID')}] ${msg}${data!==undefined?'\n'+JSON.stringify(data,null,2):''}`;$('log').textContent=( $('log').textContent==='Belum ada pengujian.'?'':$('log').textContent+'\n\n')+line;$('log').scrollTop=$('log').scrollHeight;}
function safeError(e){return {code:String(e?.code||''),message:String(e?.message||e||'Error')};}
function publicResult(x){if(!x||typeof x!=='object')return x;const clone=JSON.parse(JSON.stringify(x));const scrub=o=>{if(!o||typeof o!=='object')return;for(const k of Object.keys(o)){if(/token|pin|code/i.test(k))o[k]='[REDACTED]';else if(typeof o[k]==='object')scrub(o[k]);}};scrub(clone);return clone;}

function renderTests(){ $('testList').innerHTML=tests.map((t,i)=>`<div class="test-row" id="test-${t[0]}"><div class="test-index">${i+1}</div><div><strong>${esc(t[1])}</strong><small>${esc(t[2])}</small></div><span class="badge neutral">BELUM</span></div>`).join(''); updateSummary();}
function mark(id,status,detail=''){const row=$(`test-${id}`);if(!row)return;const b=row.querySelector('.badge');b.className=`badge ${status}`;b.textContent=status==='pass'?'LULUS':status==='fail'?'GAGAL':status==='running'?'PROSES':'SKIP';if(detail)row.querySelector('small').textContent=detail; if(state.report?.tests)state.report.tests[id]={status,detail};updateSummary();}
function updateSummary(){const vals=state.report?.tests||{};const counts={pass:0,fail:0,running:0,skip:0,all:tests.length};Object.values(vals).forEach(x=>{if(counts[x.status]!=null)counts[x.status]++;});$('summaryGrid').innerHTML=[['Total',counts.all],['Lulus',counts.pass],['Gagal',counts.fail],['Proses',counts.running],['Skip',counts.skip]].map(x=>`<div class="summary-card"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');}
function assert(cond,message){if(!cond)throw new Error(message);}
function values(obj,key){return Array.isArray(obj?.[key])?obj[key]:[];}

function config(){return {endpoint:$('backendUrl').value.trim(),phone:$('testPhone').value.trim(),pins:{farmasi:$('pinFarmasi').value.trim(),courier1:$('pinKurir1').value.trim(),courier2:$('pinKurir2').value.trim(),admin:$('pinAdmin').value.trim(),management:$('pinManagement').value.trim()}};}
function validateConfig(c){assert(/^https:\/\/script\.google\.com\/macros\/s\/[^/]+\/exec(?:\?.*)?$/.test(c.endpoint),'URL backend harus deployment /exec.');assert(c.phone,'Nomor WA uji wajib diisi.');Object.entries(c.pins).forEach(([k,v])=>assert(v,`PIN ${k} wajib diisi.`));}

async function initApi(endpoint){state.transport?.destroy();state.transport=new AppsScriptFormTransport({endpoint,timeoutMs:30000,onState:s=>{$('backendBadge').className=`badge ${s.ready?'pass':'running'}`;$('backendBadge').textContent=s.message||'...';}});state.api=new PengantaranApi(state.transport);return state.transport.connect();}
async function loginRole(pin,expected,key){const r=await state.api.login(pin,{clientId:`QA6A-${key}-${state.baseId}`,userAgent:navigator.userAgent,origin:location.origin});const role=String(r.data?.user?.role||'').trim().toUpperCase();assert(role===expected,`PIN ${key} login sebagai ${role||'role kosong'}, seharusnya ${expected}.`);state.tokens[key]=r.data.token;state.users[key]=r.data.user;return r.data.user;}
async function logoutAll(){for(const t of Object.values(state.tokens)){try{await state.api.logout(t);}catch(_){}}state.tokens={};}

function chooseArea(master){const areas=values(master,'areas');const active=areas.find(a=>String(a.status||'').toUpperCase()==='AKTIF')||areas[0];assert(active&&active.key,'Master wilayah aktif tidak tersedia.');return active;}
function payload(tag,area,phone){return {rm:`QA6A-${state.baseId}-${tag}`,name:`PASIEN UJI 6A ${tag}`,phone,recipient:`PENERIMA UJI ${tag}`,address:`ALAMAT DUMMY QA TAHAP 6A ${tag}`,areaKey:area.key,landmark:`PATOKAN DUMMY QA 6A ${tag}`};}
async function create(tag,area,phone){const r=await state.api.createDelivery(state.tokens.farmasi,payload(tag,area,phone));assert(r.data?.record?.['ID Sistem'],`Pendaftaran ${tag} gagal membuat ID Sistem.`);state.created.push(r.data.record['ID Sistem']);return r.data.record;}
async function ready(id){const r=await state.api.markReady(state.tokens.farmasi,id);return r.data?.record;}
function getReceiptCode(message){const s=String(message||'');let m=/kode(?:\s+penerimaan)?[^0-9]{0,30}(\d{4})/i.exec(s);if(!m)m=/(?:^|\D)(\d{4})(?:\D|$)/.exec(s);return m?m[1]:'';}
async function codeFor(id){const r=await state.api.registrationWa(state.tokens.farmasi,id);const code=getReceiptCode(r.data?.waAction?.message);assert(/^\d{4}$/.test(code),'Kode penerimaan 4 digit tidak dapat diekstrak dari template WA.');return code;}
function noIdentity(row){const keys=Object.keys(row||{}).map(k=>k.toLowerCase());const forbidden=['name','nama','rm','address','alamat','phone','whatsapp','wa','recipient','penerima','landmark','patokan'];return !keys.some(k=>forbidden.some(f=>k===f||k.includes(f)));}

async function runTest(id,fn){if(state.stop){mark(id,'skip','Dihentikan atas permintaan pengguna.');return null;}mark(id,'running');try{const result=await fn();mark(id,'pass',result?.detail||tests.find(t=>t[0]===id)?.[2]||'Lulus.');log(`${id.toUpperCase()} ✓`,publicResult(result));return result;}catch(e){mark(id,'fail',e.message);log(`${id.toUpperCase()} ✗`,safeError(e));throw e;}}

async function fullRun(){const c=config();try{validateConfig(c);}catch(e){alert(e.message);return;}
  $('runBtn').disabled=true;$('connectBtn').disabled=true;$('stopBtn').disabled=false;$('downloadBtn').disabled=true;state.stop=false;state.baseId=nowId();state.created=[];state.report={version:'6A.1',startedAt:new Date().toISOString(),baseId:state.baseId,frontendOrigin:location.origin,backendVersion:'',users:{},tests:{},createdIds:[],notes:[]};renderTests();$('log').textContent='';
  let area,bootstrap,claimWinner,claimLoser;
  try{
    await runTest('backend',async()=>{const ping=await initApi(c.endpoint);state.report.backendVersion=ping.data?.version||'';const u1=await loginRole(c.pins.farmasi,'FARMASI','farmasi');const u2=await loginRole(c.pins.courier1,'KURIR','courier1');const u3=await loginRole(c.pins.courier2,'KURIR','courier2');const u4=await loginRole(c.pins.admin,'ADMIN','admin');const u5=await loginRole(c.pins.management,'MANAJEMEN','management');assert(String(u2.name)!==String(u3.name),'Kurir 1 dan Kurir 2 harus akun berbeda untuk uji perebutan tugas.');state.report.users={farmasi:u1.name,courier1:u2.name,courier2:u3.name,admin:u4.name,management:u5.name};bootstrap=await state.api.farmasiBootstrap(state.tokens.farmasi);state.master=bootstrap.data?.master||{};area=chooseArea(state.master);return {detail:`Backend ${ping.data?.version||'-'}; lima login role valid; area uji ${area.village||area.key}.`};});

    let raceRecord;
    await runTest('privacy',async()=>{raceRecord=await create('RACE',area,c.phone);await ready(raceRecord['ID Sistem']);const rows=await state.api.courierRows(state.tokens.courier1);const item=(rows.data?.ready||[]).find(x=>x.id===raceRecord['ID Sistem']);assert(item,'Paket RACE tidak muncul di antrean SIAP Kurir.');assert(noIdentity(item),'Payload antrean SIAP membocorkan identitas/detail pasien sebelum claim.');return {detail:'Antrean SIAP hanya berisi ID/wilayah/waktu/status cakupan; identitas pasien tidak ada.'};});

    await runTest('duplicate',async()=>{const dup=await state.api.createDelivery(state.tokens.farmasi,payload('RACE',area,c.phone));assert(dup.data?.requiresDuplicateConfirmation===true,'Backend tidak meminta konfirmasi duplikasi untuk No. RM aktif yang sama.');return {detail:'Duplikasi aktif terdeteksi dan tidak disimpan otomatis tanpa konfirmasi.'};});

    await runTest('race',async()=>{const id=raceRecord['ID Sistem'];const [a,b]=await Promise.allSettled([state.api.claimTask(state.tokens.courier1,id),state.api.claimTask(state.tokens.courier2,id)]);const success=[a,b].filter(x=>x.status==='fulfilled');const failed=[a,b].filter(x=>x.status==='rejected');assert(success.length===1&&failed.length===1,`Ekspektasi 1 claim berhasil + 1 ditolak; hasil ${success.length} berhasil, ${failed.length} ditolak.`);claimWinner=a.status==='fulfilled'?'courier1':'courier2';claimLoser=claimWinner==='courier1'?'courier2':'courier1';const rec=success[0].value.data?.record;assert(rec?.name&&rec?.address,'Setelah claim berhasil, detail pasien/alamat belum terbuka untuk Kurir pemenang.');return {detail:`Race aman: ${state.users[claimWinner].name} menang; ${state.users[claimLoser].name} ditolak.`};});

    await runTest('code',async()=>{const id=raceRecord['ID Sistem'];const code=await codeFor(id);let wrong=code==='0000'?'9999':'0000';const bad=await state.api.completeVerified(state.tokens[claimWinner],id,{recipientName:'PENERIMA UJI RACE',relationship:values(state.master,'receiptRelationships')[0]||'PASIEN SENDIRI',mode:'CODE',code:wrong,noCodeReason:''});assert(bad.data?.codeInvalid||bad.data?.codeLocked,'Kode salah tidak ditolak backend.');const ok=await state.api.completeVerified(state.tokens[claimWinner],id,{recipientName:'PENERIMA UJI RACE',relationship:values(state.master,'receiptRelationships')[0]||'PASIEN SENDIRI',mode:'CODE',code,noCodeReason:''});assert(!ok.data?.verificationPending,'Kode benar malah masuk verifikasi manual.');assert(String(ok.data?.record?.status||'').toUpperCase()==='TERKIRIM','Kode benar tidak menghasilkan status TERKIRIM.');return {detail:'Kode salah ditolak; kode benar menyelesaikan pengantaran dengan verifikasi langsung.'};});

    await runTest('manual',async()=>{const rec=await create('MANUAL',area,c.phone);await ready(rec['ID Sistem']);const claim=await state.api.claimTask(state.tokens.courier1,rec['ID Sistem']);assert(claim.data?.record?.id,'Kurir gagal mengambil kasus MANUAL.');const masterCourier=(await state.api.courierBootstrap(state.tokens.courier1)).data?.master||{};const reason=values(masterCourier,'noCodeReasons')[0];const relationship=values(masterCourier,'receiptRelationships')[0]||values(state.master,'receiptRelationships')[0];assert(reason,'Master alasan tanpa kode kosong.');const done=await state.api.completeVerified(state.tokens.courier1,rec['ID Sistem'],{recipientName:'PENERIMA UJI MANUAL',relationship:relationship||'PASIEN SENDIRI',mode:'NO_CODE',code:'',noCodeReason:reason});assert(done.data?.verificationPending===true,'Tanpa kode tidak masuk status menunggu verifikasi manual.');let pending=await state.api.adminPendingVerifications(state.tokens.admin);assert((pending.data?.rows||[]).some(x=>x['ID Sistem']===rec['ID Sistem']),'Kasus tanpa kode tidak muncul di antrean verifikasi Admin.');const ab=await state.api.adminBootstrap(state.tokens.admin);const method=values(ab.data?.master||{},'manualVerificationMethods')[0]||'WHATSAPP';await state.api.adminManualVerifyReceipt(state.tokens.admin,rec['ID Sistem'],method,'QA 6A: penerimaan dummy terkonfirmasi.');pending=await state.api.adminPendingVerifications(state.tokens.admin);assert(!(pending.data?.rows||[]).some(x=>x['ID Sistem']===rec['ID Sistem']),'Kasus masih muncul setelah verifikasi manual disimpan.');return {detail:'Tanpa kode masuk antrean Admin dan hilang setelah verifikasi manual.'};});

    await runTest('failed',async()=>{const rec=await create('FAILED',area,c.phone);await ready(rec['ID Sistem']);await state.api.claimTask(state.tokens.courier1,rec['ID Sistem']);const cb=await state.api.courierBootstrap(state.tokens.courier1);const m=cb.data?.master||{};const reason=values(m,'failureReasons')[0],follow=values(m,'failureFollowUps')[0];assert(reason&&follow,'Master alasan/tindak lanjut gagal belum tersedia.');const done=await state.api.failTask(state.tokens.courier1,rec['ID Sistem'],{reason,followUp:follow,detail:'QA 6A gagal antar dummy'});assert(String(done.data?.record?.status||'').toUpperCase()==='GAGAL ANTAR','Status gagal antar tidak tersimpan.');const hist=await state.api.courierHistory(state.tokens.courier1,100);assert((hist.data?.rows||[]).some(x=>x.id===rec['ID Sistem']&&String(x.status).toUpperCase()==='GAGAL ANTAR'),'Kasus gagal tidak muncul di riwayat Kurir.');return {detail:'Alasan dan tindak lanjut gagal tersimpan serta muncul di riwayat Kurir.'};});

    await runTest('incident',async()=>{const rec=await create('INCIDENT',area,c.phone);await ready(rec['ID Sistem']);await state.api.claimTask(state.tokens.courier1,rec['ID Sistem']);const cb=await state.api.courierBootstrap(state.tokens.courier1);const m=cb.data?.master||{};const type=values(m,'incidentTypes')[0],delay=values(m,'delayEstimates')[0];assert(type&&delay,'Master jenis kendala/perkiraan keterlambatan kosong.');const rep=await state.api.reportIncident(state.tokens.courier1,{type,detail:'QA 6A kendala dummy',delayEstimate:delay});const incident=rep.data?.incident;assert(incident?.id,'Kendala tidak menghasilkan ID.');assert(String(incident.status||'').toUpperCase()==='AKTIF','Kendala baru tidak berstatus AKTIF.');await state.api.resolveIncident(state.tokens.courier1,incident.id,'QA 6A kendala selesai.');let list=await state.api.adminIncidents(state.tokens.admin);const item=(list.data?.rows||[]).find(x=>x.id===incident.id);assert(item,'Kendala tidak muncul di Admin.');if(String(item.verificationStatus||'').toUpperCase()==='MENUNGGU VERIFIKASI')await state.api.adminVerifyIncident(state.tokens.admin,incident.id,'TERVERIFIKASI','QA 6A kendala diverifikasi Admin.');list=await state.api.adminIncidents(state.tokens.admin);const verified=(list.data?.rows||[]).find(x=>x.id===incident.id);assert(String(verified?.verificationStatus||'').toUpperCase()==='TERVERIFIKASI','Kendala tidak menjadi TERVERIFIKASI.');const fmaster=(await state.api.courierBootstrap(state.tokens.courier1)).data?.master||{};const reason=values(fmaster,'failureReasons')[0],follow=values(fmaster,'failureFollowUps')[0];await state.api.failTask(state.tokens.courier1,rec['ID Sistem'],{reason,followUp:follow,detail:'QA cleanup case incident'});return {detail:'Kendala aktif, diselesaikan Kurir, terlihat dan diverifikasi Admin.'};});

    await runTest('management',async()=>{const d=localDate();const res=await state.api.managementData(state.tokens.management,d,d,'DAFTAR');const k=res.data?.dashboard?.kpi||{};assert(Number(k.total||0)>=state.created.length,`KPI total hari ini ${k.total||0} lebih kecil dari ${state.created.length} kasus QA yang dibuat.`);assert(Number(k.delivered||0)>=2,'KPI terkirim belum mencerminkan minimal dua kasus selesai (kode + manual).');assert(Number(k.failed||0)>=2,'KPI gagal belum mencerminkan minimal dua kasus gagal (FAILED + cleanup INCIDENT).');return {detail:`KPI terbaca: total ${k.total||0}, terkirim ${k.delivered||0}, gagal ${k.failed||0}.`};});

    await runTest('audit',async()=>{const res=await state.api.adminAuditRows(state.tokens.admin,200);const rows=res.data?.rows||[];assert(rows.length>0,'Audit Admin kosong setelah regression test.');const qa=rows.filter(x=>String(x.note||'').includes('QA 6A')||state.created.includes(String(x.id||'')));assert(qa.length>0,'Jejak aktivitas QA 6A tidak ditemukan pada audit terbaru.');return {detail:`Audit aktif; ${qa.length} baris terkait skenario QA terdeteksi.`};});

  }catch(e){state.report.notes.push(`RUN STOPPED: ${e.message}`);for(const t of tests){if(!state.report.tests[t[0]])mark(t[0],'skip','Tidak dijalankan karena langkah sebelumnya gagal.');}}
  finally{state.report.createdIds=[...state.created];state.report.finishedAt=new Date().toISOString();state.report.passed=Object.values(state.report.tests).filter(x=>x.status==='pass').length;state.report.failed=Object.values(state.report.tests).filter(x=>x.status==='fail').length;state.report.skipped=Object.values(state.report.tests).filter(x=>x.status==='skip').length;await logoutAll();$('runBtn').disabled=false;$('connectBtn').disabled=false;$('stopBtn').disabled=true;$('downloadBtn').disabled=false;updateSummary();log('REGRESSION 6A SELESAI',{passed:state.report.passed,failed:state.report.failed,skipped:state.report.skipped,createdIds:state.created});}
}

async function testBackend(){const c=config();try{validateConfig(c);$('connectBtn').disabled=true;const p=await initApi(c.endpoint);log('BACKEND ✓',{version:p.data?.version,modules:p.data?.activeModules});}catch(e){log('BACKEND ✗',safeError(e));alert(e.message);}finally{$('connectBtn').disabled=false;}}
function downloadReport(){if(!state.report)return;const clean=JSON.stringify(state.report,null,2);const blob=new Blob([clean],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`Regression_6A_${state.baseId||nowId()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

window.addEventListener('DOMContentLoaded',()=>{renderTests();$('backendUrl').value=localStorage.getItem('antarobat_backend_url')||'';$('connectBtn').addEventListener('click',testBackend);$('runBtn').addEventListener('click',fullRun);$('stopBtn').addEventListener('click',()=>{state.stop=true;$('stopBtn').disabled=true;log('STOP REQUESTED','Runner akan berhenti setelah langkah yang sedang berjalan selesai.');});$('downloadBtn').addEventListener('click',downloadReport);$('clearBtn').addEventListener('click',()=>{$('log').textContent='Belum ada pengujian.';});});
